server:
  port: 9527
show:
  text: hello-my-server-is-A_port-is-9000

spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 10GB #最大请求文件的大小
      max-file-size: 10GB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入
  datasource:
    url: jdbc:mysql://localhost:3306/wjup?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver